"""Initial Migration

Revision ID: 72dc8b4a5b08
Revises: f224595437c5
Create Date: 2019-09-29 21:17:04.076030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72dc8b4a5b08'
down_revision = 'f224595437c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('subscribes_userId_fkey', 'subscribes', type_='foreignkey')
    op.drop_column('subscribes', 'userId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribes', sa.Column('userId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('subscribes_userId_fkey', 'subscribes', 'users', ['userId'], ['id'])
    # ### end Alembic commands ###
